import type {
  User,
  Visitor,
  Complaint,
  Bill,
  FacilityBooking,
  Announcement,
  Notification,
  ServiceRequest,
  Facility,
  Vendor,
  Property,
  Poll,
  Event,
  StaffMember,
  UserRole,
} from "@/types";

export const mockUsers: Record<string, User> = {
  resident: {
    id: "usr_001",
    name: "Aryan Sharma",
    email: "aryan.sharma@email.com",
    phone: "+91 98765 43210",
    role: "resident",
    flat: "B-402",
    tower: "Tower B",
    society: "Maple Heights",
    isVerified: true,
    joinedDate: "2022-03-15",
  },
  committee: {
    id: "usr_002",
    name: "Priya Mehta",
    email: "priya.mehta@email.com",
    phone: "+91 87654 32109",
    role: "committee",
    flat: "A-101",
    tower: "Tower A",
    society: "Maple Heights",
    isVerified: true,
    joinedDate: "2021-06-01",
  },
  security: {
    id: "usr_003",
    name: "Rajan Kumar",
    email: "rajan.kumar@email.com",
    phone: "+91 76543 21098",
    role: "security",
    society: "Maple Heights",
    isVerified: true,
    joinedDate: "2020-01-10",
  },
  maintenance: {
    id: "usr_004",
    name: "Suresh Patel",
    email: "suresh.patel@email.com",
    phone: "+91 65432 10987",
    role: "maintenance",
    society: "Maple Heights",
    isVerified: true,
    joinedDate: "2020-05-20",
  },
  vendor: {
    id: "usr_005",
    name: "Vikram Singh",
    email: "vikram.singh@email.com",
    phone: "+91 54321 09876",
    role: "vendor",
    society: "Maple Heights",
    isVerified: true,
    joinedDate: "2021-11-15",
  },
  builder: {
    id: "usr_006",
    name: "Amit Kapoor",
    email: "amit.kapoor@email.com",
    phone: "+91 43210 98765",
    role: "builder",
    society: "Maple Heights",
    isVerified: true,
    joinedDate: "2019-01-01",
  },
  admin: {
    id: "usr_007",
    name: "Neha Gupta",
    email: "neha.gupta@email.com",
    phone: "+91 32109 87654",
    role: "admin",
    society: "MapleOne Platform",
    isVerified: true,
    joinedDate: "2018-06-01",
  },
};

export const mockVisitors: Visitor[] = [
  {
    id: "vis_001",
    name: "Rahul Verma",
    phone: "+91 91234 56789",
    purpose: "Personal Visit",
    flatNo: "B-402",
    tower: "Tower B",
    entryTime: new Date(Date.now() - 3600000).toISOString(),
    status: "inside",
    type: "visitor",
    vehicleNo: "MH 01 AB 1234",
  },
  {
    id: "vis_002",
    name: "Amazon Delivery",
    phone: "+91 80001 00001",
    purpose: "Package Delivery",
    flatNo: "A-201",
    tower: "Tower A",
    entryTime: new Date(Date.now() - 1800000).toISOString(),
    exitTime: new Date(Date.now() - 900000).toISOString(),
    status: "exited",
    type: "delivery",
  },
  {
    id: "vis_003",
    name: "Sunita Devi",
    phone: "+91 70002 00002",
    purpose: "Domestic Help",
    flatNo: "C-303",
    tower: "Tower C",
    entryTime: new Date(Date.now() - 7200000).toISOString(),
    status: "inside",
    type: "staff",
  },
  {
    id: "vis_004",
    name: "Kavita Nair",
    phone: "+91 60003 00003",
    purpose: "Guest Visit",
    flatNo: "B-402",
    tower: "Tower B",
    entryTime: "",
    status: "pending",
    type: "visitor",
  },
  {
    id: "vis_005",
    name: "Zomato Delivery",
    phone: "+91 80004 00004",
    purpose: "Food Delivery",
    flatNo: "D-501",
    tower: "Tower D",
    entryTime: new Date(Date.now() - 600000).toISOString(),
    exitTime: new Date(Date.now() - 300000).toISOString(),
    status: "exited",
    type: "delivery",
  },
  {
    id: "vis_006",
    name: "Mohit Joshi",
    phone: "+91 99888 77766",
    purpose: "Relative Visit",
    flatNo: "A-110",
    tower: "Tower A",
    entryTime: new Date(Date.now() - 900000).toISOString(),
    status: "inside",
    type: "visitor",
    vehicleNo: "DL 05 CD 5678",
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: "cmp_001",
    title: "Water Leakage in Bathroom",
    description: "There is continuous water leakage from the ceiling in the master bedroom bathroom. It has been causing damage to the flooring.",
    category: "Plumbing",
    status: "in-progress",
    priority: "high",
    raisedBy: "Aryan Sharma",
    raisedByFlat: "B-402",
    assignedTo: "Suresh Patel",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "cmp_002",
    title: "Lift Not Working",
    description: "The elevator in Tower C has been out of order since yesterday morning. Elderly residents are facing difficulty.",
    category: "Electrical",
    status: "open",
    priority: "urgent",
    raisedBy: "Priya Mehta",
    raisedByFlat: "A-101",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "cmp_003",
    title: "Parking Area Lighting Issue",
    description: "The lights in Level B2 parking are not working for the past week. Creates safety issues at night.",
    category: "Electrical",
    status: "resolved",
    priority: "medium",
    raisedBy: "Rajesh Khanna",
    raisedByFlat: "C-203",
    assignedTo: "Suresh Patel",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    rating: 4,
    feedback: "Issue resolved quickly. Good work!",
  },
  {
    id: "cmp_004",
    title: "Garbage Not Collected",
    description: "The garbage bins on Floor 5 of Tower B have not been emptied for 3 days. Causing foul smell.",
    category: "Housekeeping",
    status: "open",
    priority: "medium",
    raisedBy: "Sunita Agarwal",
    raisedByFlat: "B-503",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "cmp_005",
    title: "Swimming Pool Maintenance Required",
    description: "The swimming pool water appears murky and needs chemical treatment and cleaning urgently.",
    category: "Amenities",
    status: "in-progress",
    priority: "high",
    raisedBy: "Vikram Rathore",
    raisedByFlat: "D-601",
    assignedTo: "Pool Vendor",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const mockBills: Bill[] = [
  {
    id: "bill_001",
    residentId: "usr_001",
    residentName: "Aryan Sharma",
    flat: "B-402",
    tower: "Tower B",
    month: "May",
    year: 2025,
    maintenanceAmount: 3500,
    waterCharges: 800,
    electricityCharges: 1200,
    parkingCharges: 500,
    penalty: 0,
    discount: 200,
    totalAmount: 5800,
    dueDate: new Date(Date.now() + 86400000 * 10).toISOString(),
    status: "pending",
  },
  {
    id: "bill_002",
    residentId: "usr_001",
    residentName: "Aryan Sharma",
    flat: "B-402",
    tower: "Tower B",
    month: "April",
    year: 2025,
    maintenanceAmount: 3500,
    waterCharges: 750,
    electricityCharges: 1100,
    parkingCharges: 500,
    penalty: 0,
    discount: 0,
    totalAmount: 5850,
    dueDate: new Date(Date.now() - 86400000 * 20).toISOString(),
    paidDate: new Date(Date.now() - 86400000 * 22).toISOString(),
    status: "paid",
    paymentMethod: "UPI",
    transactionId: "TXN20250410001",
  },
  {
    id: "bill_003",
    residentId: "usr_008",
    residentName: "Rajesh Kumar",
    flat: "A-201",
    tower: "Tower A",
    month: "May",
    year: 2025,
    maintenanceAmount: 3500,
    waterCharges: 900,
    electricityCharges: 1400,
    parkingCharges: 1000,
    penalty: 350,
    discount: 0,
    totalAmount: 7150,
    dueDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    status: "overdue",
  },
  {
    id: "bill_004",
    residentId: "usr_009",
    residentName: "Meena Reddy",
    flat: "C-303",
    tower: "Tower C",
    month: "May",
    year: 2025,
    maintenanceAmount: 3500,
    waterCharges: 650,
    electricityCharges: 950,
    parkingCharges: 500,
    penalty: 0,
    discount: 350,
    totalAmount: 5250,
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    status: "pending",
  },
];

export const mockBookings: FacilityBooking[] = [
  {
    id: "bkng_001",
    facilityName: "Clubhouse",
    facilityType: "clubhouse",
    residentId: "usr_001",
    residentName: "Aryan Sharma",
    flat: "B-402",
    date: new Date(Date.now() + 86400000 * 3).toISOString().split("T")[0],
    startTime: "06:00",
    endTime: "08:00",
    status: "confirmed",
    amount: 500,
    purpose: "Birthday Party",
    guestCount: 25,
  },
  {
    id: "bkng_002",
    facilityName: "Swimming Pool",
    facilityType: "pool",
    residentId: "usr_001",
    residentName: "Aryan Sharma",
    flat: "B-402",
    date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    startTime: "07:00",
    endTime: "08:00",
    status: "confirmed",
    amount: 200,
    guestCount: 2,
  },
  {
    id: "bkng_003",
    facilityName: "Badminton Court",
    facilityType: "sports",
    residentId: "usr_010",
    residentName: "Kavya Nair",
    flat: "D-104",
    date: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0],
    startTime: "18:00",
    endTime: "20:00",
    status: "pending",
    amount: 300,
    guestCount: 4,
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann_001",
    title: "Water Supply Interruption – May 20",
    content: "Dear Residents, please note that there will be a scheduled maintenance of the water supply system on May 20, 2025 from 9:00 AM to 5:00 PM. Kindly store sufficient water. We apologize for the inconvenience.",
    category: "Maintenance",
    postedBy: "Society Committee",
    postedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    priority: "important",
    targetRoles: ["resident", "committee", "security", "maintenance"],
    views: 234,
  },
  {
    id: "ann_002",
    title: "Annual General Meeting – June 1, 2025",
    content: "The Annual General Meeting of Maple Heights Resident Welfare Association will be held on June 1, 2025 at 11:00 AM in the Community Hall. All residents are requested to attend. Agenda includes election of new committee members and annual budget discussion.",
    category: "Society",
    postedBy: "RWA President",
    postedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    priority: "important",
    targetRoles: ["resident", "committee"],
    views: 312,
  },
  {
    id: "ann_003",
    title: "Summer Sports Carnival – Registration Open!",
    content: "We are thrilled to announce the MapleOne Summer Sports Carnival 2025! Events include cricket, badminton, swimming relay, and kids' sports. Register now for exciting prizes and community bonding. Registration closes May 25, 2025.",
    category: "Events",
    postedBy: "Events Committee",
    postedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    priority: "normal",
    targetRoles: ["resident"],
    views: 178,
  },
  {
    id: "ann_004",
    title: "New Security Protocol for Visitor Entry",
    content: "Effective from June 1, 2025, all visitors must be pre-approved through the MapleOne app by the resident being visited. Walk-in approvals without pre-registration will be limited to emergency cases only. Security guards will verify QR codes mandatorily.",
    category: "Security",
    postedBy: "Security Committee",
    postedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    priority: "urgent",
    targetRoles: ["resident", "security", "committee"],
    views: 456,
  },
];

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: "svc_001",
    type: "Plumbing",
    description: "Kitchen tap has been dripping continuously for 2 days. Need urgent repair.",
    residentId: "usr_001",
    residentName: "Aryan Sharma",
    flat: "B-402",
    status: "assigned",
    priority: "medium",
    assignedTo: "Ramesh (Plumber)",
    vendorId: "vnd_001",
    scheduledDate: new Date(Date.now() + 86400000).toISOString(),
    amount: 450,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "svc_002",
    type: "Electrical",
    description: "One electrical outlet in the living room is not working. Need to check and fix.",
    residentId: "usr_001",
    residentName: "Aryan Sharma",
    flat: "B-402",
    status: "completed",
    priority: "low",
    assignedTo: "Suresh (Electrician)",
    vendorId: "vnd_002",
    scheduledDate: new Date(Date.now() - 86400000 * 3).toISOString(),
    completedDate: new Date(Date.now() - 86400000 * 2).toISOString(),
    amount: 300,
    rating: 5,
    feedback: "Excellent work, fixed quickly!",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "svc_003",
    type: "Plumbing",
    description: "Bathroom flush is leaking water. Water is flowing continuously.",
    residentId: "usr_002",
    residentName: "Priya Mehta",
    flat: "A-101",
    status: "pending",
    priority: "high",
    vendorId: "vnd_001",
    amount: 350,
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: "svc_004",
    type: "Electrical",
    description: "Geyser not heating up in the master bedroom washroom. Need switch check.",
    residentId: "usr_002",
    residentName: "Priya Mehta",
    flat: "A-101",
    status: "pending",
    priority: "medium",
    vendorId: "vnd_002",
    amount: 500,
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: "svc_005",
    type: "Housekeeping",
    description: "Deep balcony cleaning needed before society festival event.",
    residentId: "usr_001",
    residentName: "Aryan Sharma",
    flat: "B-402",
    status: "completed",
    priority: "low",
    assignedTo: "Vijay (Cleaning)",
    vendorId: "vnd_003",
    scheduledDate: new Date(Date.now() - 86400000).toISOString(),
    completedDate: new Date(Date.now() - 86400000 + 4000000).toISOString(),
    amount: 600,
    rating: 4,
    feedback: "Good work but came 15 minutes late.",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "svc_006",
    type: "Pest Control",
    description: "Termite inspection required in the main kitchen cabinets.",
    residentId: "usr_001",
    residentName: "Aryan Sharma",
    flat: "B-402",
    status: "assigned",
    priority: "medium",
    assignedTo: "Karan (Pest Experts)",
    vendorId: "vnd_004",
    scheduledDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    amount: 1200,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const mockFacilities: Facility[] = [
  {
    id: "fac_001",
    name: "Clubhouse",
    type: "clubhouse",
    capacity: 100,
    pricePerHour: 500,
    amenities: ["AC", "Sound System", "Catering Allowed", "Projector", "Stage"],
    availability: ["Monday-Sunday: 6AM-11PM"],
    isAvailable: true,
  },
  {
    id: "fac_002",
    name: "Swimming Pool",
    type: "pool",
    capacity: 30,
    pricePerHour: 200,
    amenities: ["Changing Rooms", "Lifeguard", "Pool Towels"],
    availability: ["Monday-Sunday: 6AM-9PM"],
    isAvailable: true,
  },
  {
    id: "fac_003",
    name: "Gymnasium",
    type: "gym",
    capacity: 20,
    pricePerHour: 100,
    amenities: ["Cardio Equipment", "Weights", "AC", "Trainer Available"],
    availability: ["Monday-Sunday: 5AM-10PM"],
    isAvailable: true,
  },
  {
    id: "fac_004",
    name: "Badminton Court",
    type: "sports",
    capacity: 8,
    pricePerHour: 150,
    amenities: ["Rackets Available", "Shuttlecocks", "Lighting"],
    availability: ["Monday-Sunday: 6AM-10PM"],
    isAvailable: true,
  },
  {
    id: "fac_005",
    name: "Community Hall",
    type: "hall",
    capacity: 200,
    pricePerHour: 1000,
    amenities: ["AC", "Sound System", "Projector", "Stage", "Catering Area"],
    availability: ["Monday-Sunday: 8AM-11PM"],
    isAvailable: false,
    maintenanceSchedule: "May 22-24",
  },
  {
    id: "fac_006",
    name: "Guest Room",
    type: "guestroom",
    capacity: 4,
    pricePerHour: 800,
    amenities: ["AC", "WiFi", "Attached Bath", "TV", "Mini Kitchen"],
    availability: ["Available for 1-3 night stays"],
    isAvailable: true,
  },
];

export const mockVendors: Vendor[] = [
  {
    id: "vnd_001",
    name: "Ramesh Kumar",
    businessName: "Ramesh Plumbing Services",
    category: "Plumbing",
    phone: "+91 91111 22222",
    email: "ramesh.plumbing@gmail.com",
    rating: 4.8,
    totalJobs: 156,
    completedJobs: 148,
    earnings: 74000,
    isApproved: true,
    services: ["Tap Repair", "Pipe Fixing", "Drain Cleaning", "Geyser Installation"],
    joinedDate: "2021-03-10",
  },
  {
    id: "vnd_002",
    name: "Suresh Yadav",
    businessName: "PowerFix Electricals",
    category: "Electrical",
    phone: "+91 82222 33333",
    email: "powerfix@gmail.com",
    rating: 4.6,
    totalJobs: 203,
    completedJobs: 195,
    earnings: 97500,
    isApproved: true,
    services: ["Wiring", "MCB Replacement", "Fan Installation", "CCTV Setup"],
    joinedDate: "2020-08-15",
  },
  {
    id: "vnd_003",
    name: "CleanHome Services",
    businessName: "CleanHome Professional Services",
    category: "Housekeeping",
    phone: "+91 73333 44444",
    email: "cleanhome@gmail.com",
    rating: 4.5,
    totalJobs: 412,
    completedJobs: 400,
    earnings: 200000,
    isApproved: true,
    services: ["Deep Cleaning", "Sofa Cleaning", "Carpet Cleaning", "Post-Renovation Cleaning"],
    joinedDate: "2020-01-01",
  },
];

export const mockProperties: Property[] = [
  {
    id: "prop_001",
    societyName: "Maple Heights",
    address: "Sector 62, Noida",
    city: "Noida, UP",
    totalTowers: 6,
    totalFlats: 480,
    occupiedFlats: 421,
    vacantFlats: 59,
    totalResidents: 1246,
    buildYear: 2018,
    amenities: ["Swimming Pool", "Gym", "Clubhouse", "Badminton Court", "Children's Play Area", "Jogging Track"],
    monthlyMaintenance: 3500,
    healthScore: 87,
  },
  {
    id: "prop_002",
    societyName: "Maple Gardens",
    address: "Sector 78, Gurgaon",
    city: "Gurgaon, Haryana",
    totalTowers: 4,
    totalFlats: 320,
    occupiedFlats: 298,
    vacantFlats: 22,
    totalResidents: 834,
    buildYear: 2020,
    amenities: ["Swimming Pool", "Gym", "Community Hall", "Tennis Court", "Kids Pool"],
    monthlyMaintenance: 4000,
    healthScore: 92,
  },
];

export const mockPolls: Poll[] = [
  {
    id: "poll_001",
    question: "What should be the new gym timing to accommodate all residents?",
    options: [
      { id: "opt_1", text: "5AM - 10PM (Extended)", votes: 87 },
      { id: "opt_2", text: "6AM - 10PM (Current)", votes: 42 },
      { id: "opt_3", text: "5AM - 11PM (Night Extended)", votes: 31 },
    ],
    createdBy: "Society Committee",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    expiresAt: new Date(Date.now() + 86400000 * 4).toISOString(),
    totalVotes: 160,
    status: "active",
  },
  {
    id: "poll_002",
    question: "Should we install EV charging stations in the parking area?",
    options: [
      { id: "opt_4", text: "Yes, definitely!", votes: 124 },
      { id: "opt_5", text: "Yes, but only if cost shared equally", votes: 56 },
      { id: "opt_6", text: "Not required right now", votes: 18 },
    ],
    createdBy: "RWA President",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    expiresAt: new Date(Date.now() + 86400000 * 7).toISOString(),
    totalVotes: 198,
    status: "active",
  },
];

export const mockEvents: Event[] = [
  {
    id: "evt_001",
    title: "Summer Sports Carnival 2025",
    description: "Annual sports carnival with cricket, badminton, swimming relay, and kids' activities. Great prizes and community bonding.",
    date: new Date(Date.now() + 86400000 * 15).toISOString().split("T")[0],
    time: "9:00 AM",
    venue: "Community Ground & Pool",
    organizer: "Events Committee",
    maxAttendees: 200,
    registeredCount: 134,
    category: "Sports",
    isUserRegistered: false,
  },
  {
    id: "evt_002",
    title: "Diwali Celebration Night",
    description: "Community Diwali celebration with cultural performances, rangoli competition, and fireworks display. Dinner included for all registered families.",
    date: new Date(Date.now() + 86400000 * 45).toISOString().split("T")[0],
    time: "6:00 PM",
    venue: "Clubhouse & Parking Area",
    organizer: "Cultural Committee",
    maxAttendees: 500,
    registeredCount: 218,
    category: "Festival",
    isUserRegistered: true,
  },
  {
    id: "evt_003",
    title: "Yoga & Wellness Workshop",
    description: "Expert-led yoga and meditation session for residents. Improve your physical and mental well-being in a group setting.",
    date: new Date(Date.now() + 86400000 * 5).toISOString().split("T")[0],
    time: "7:00 AM",
    venue: "Garden Area",
    organizer: "Health & Wellness Club",
    maxAttendees: 50,
    registeredCount: 38,
    category: "Wellness",
    isUserRegistered: false,
  },
];

export const mockStaff: StaffMember[] = [
  {
    id: "stf_001",
    name: "Rajan Kumar",
    role: "Security Guard",
    department: "Security",
    phone: "+91 76543 21098",
    shift: "Morning (6AM-2PM)",
    status: "active",
    joinedDate: "2020-01-10",
    salary: 18000,
    rating: 4.5,
  },
  {
    id: "stf_002",
    name: "Arun Singh",
    role: "Security Guard",
    department: "Security",
    phone: "+91 76543 21099",
    shift: "Evening (2PM-10PM)",
    status: "active",
    joinedDate: "2021-03-15",
    salary: 18000,
    rating: 4.3,
  },
  {
    id: "stf_003",
    name: "Suresh Patel",
    role: "Maintenance Lead",
    department: "Maintenance",
    phone: "+91 65432 10987",
    shift: "Day (8AM-5PM)",
    status: "active",
    joinedDate: "2020-05-20",
    salary: 25000,
    rating: 4.7,
  },
];

export function generateNotifications(role: UserRole): Notification[] {
  const base: Notification[] = [
    {
      id: `notif_${Date.now()}_1`,
      title: "Welcome to MapleOne",
      message: "Your account is now active. Explore your dashboard.",
      type: "success",
      isRead: false,
      createdAt: new Date().toISOString(),
      category: "System",
    },
    {
      id: `notif_${Date.now()}_2`,
      title: "New Announcement",
      message: "Water supply interruption scheduled for May 20.",
      type: "warning",
      isRead: false,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      category: "Announcement",
    },
  ];

  const roleSpecific: Record<UserRole, Notification[]> = {
    resident: [
      {
        id: `notif_res_1`,
        title: "Bill Due Soon",
        message: "Your maintenance bill of ₹5,800 is due in 10 days.",
        type: "warning",
        isRead: false,
        createdAt: new Date(Date.now() - 7200000).toISOString(),
        category: "Billing",
      },
      {
        id: `notif_res_2`,
        title: "Visitor Arrived",
        message: "Rahul Verma has entered your premises.",
        type: "info",
        isRead: true,
        createdAt: new Date(Date.now() - 3600000).toISOString(),
        category: "Visitor",
      },
    ],
    committee: [
      {
        id: `notif_com_1`,
        title: "New Complaint",
        message: "Urgent: Lift not working in Tower C",
        type: "error",
        isRead: false,
        createdAt: new Date(Date.now() - 1800000).toISOString(),
        category: "Complaints",
      },
    ],
    security: [
      {
        id: `notif_sec_1`,
        title: "Visitor Pending Approval",
        message: "Kavita Nair is waiting at the gate for B-402.",
        type: "warning",
        isRead: false,
        createdAt: new Date(Date.now() - 900000).toISOString(),
        category: "Visitor",
      },
    ],
    maintenance: [
      {
        id: `notif_mnt_1`,
        title: "New Work Order",
        message: "Urgent plumbing repair assigned - B-402",
        type: "warning",
        isRead: false,
        createdAt: new Date(Date.now() - 1800000).toISOString(),
        category: "WorkOrder",
      },
    ],
    vendor: [
      {
        id: `notif_vnd_1`,
        title: "New Service Request",
        message: "Plumbing job at B-402 awaiting acceptance.",
        type: "info",
        isRead: false,
        createdAt: new Date(Date.now() - 3600000).toISOString(),
        category: "Jobs",
      },
    ],
    builder: [
      {
        id: `notif_bld_1`,
        title: "Occupancy Update",
        message: "Maple Heights is now at 87.7% occupancy.",
        type: "success",
        isRead: false,
        createdAt: new Date(Date.now() - 86400000).toISOString(),
        category: "Property",
      },
    ],
    admin: [
      {
        id: `notif_adm_1`,
        title: "New Community Registered",
        message: "Maple Gardens, Gurgaon has been onboarded.",
        type: "success",
        isRead: false,
        createdAt: new Date(Date.now() - 43200000).toISOString(),
        category: "Platform",
      },
    ],
  };

  return [...base, ...(roleSpecific[role] || [])];
}


